package com.lexnicholls.lovecounter

object QuestionsRepository {
    private val questions = listOf(
        """[😂] Si Rocco de repente pudiera hablar por 24 horas, ¿qué crees que sería lo primero que diría sobre nuestra dinámica en casa?""",
        """[🤔] ¿Cuál es ese pequeño detalle de nuestra rutina diaria que más disfrutas pero que rara vez mencionas?""",
        """[🥵] ¿Cuál ha sido el lugar más inusual o el momento más inesperado donde has fantaseado conmigo?""",
        """[💭] ¿De qué manera sientes que hemos crecido más como equipo en el último año?""",
        """[😂] Si nuestra vida fuera una campaña de D&D, ¿cuáles serían nuestras clases y quién sería el verdadero jefe final de nuestro día a día?""",
        """[🤔] Si tuvieras que comer solo una receta de las que preparamos en la freidora de aire o en la olla a presión por el resto del año, ¿cuál elegirías sin dudarlo?""",
        """[🥵] ¿Qué prenda de ropa mía (incluso la de andar por casa) te resulta secretamente irresistible?""",
        """[💭] ¿Cuál es el recuerdo caminando o pasando el rato por Mosquera que guardas con más cariño?""",
        """[😂] Si tuviéramos que sobrevivir a un apocalipsis zombie usando solo los aparatos tecnológicos, teléfonos y tablets que tenemos en casa, ¿cuál sería nuestra estrategia?""",
        """[🤔] ¿Qué habilidad mía, por más inútil o específica que parezca, te sorprende o te da un poco de envidia?""",
        """[🥵] Si esta noche fuera nuestra primera cita de nuevo, pero con la confianza que ya nos tenemos, ¿cómo intentarías seducirme?""",
        """[💭] ¿Qué aspecto de nuestra comunicación crees que ha mejorado más desde que empezamos a vivir juntos?""",
        """[😂] Jugando cooperativos como Lethal Company, ¿cuál dirías que es mi peor hábito o la forma más tonta en la que suelo hacernos perder?""",
        """[🤔] ¿Qué canción o género musical te recordará siempre a nuestros primeros meses de conocernos?""",
        """[🥵] ¿Qué tipo de caricias, masajes o contacto físico te relaja más después de un día lleno de estrés?""",
        """[💭] ¿Cómo te imaginas una noche de viernes perfecta para nosotros de aquí a 10 años?""",
        """[😂] Si tuviéramos un programa de cocina juntos de batch cooking, ¿cuál sería nuestro platillo estrella y quién sería el chef gruñón?""",
        """[🤔] ¿Cuál ha sido tu momento de mayor orgullo viéndome lograr algo (ya sea en el trabajo, programando o armando algún equipo complejo)?""",
        """[🥵] ¿Qué idea atrevida o juego nuevo te gustaría que exploráramos en los próximos meses?""",
        """[💭] ¿Qué es algo específico que hago por ti que te hace sentir verdaderamente amado/a y protegido/a?""",
        """[😂] Si nuestro Pomeranian nos pusiera una calificación del 1 al 10 como cuidadores, ¿en qué punto exacto nos bajaría puntos?""",
        """[🤔] ¿Qué tradición de pareja que hemos creado de la nada es tu favorita absoluta?""",
        """[🥵] ¿En qué momento del día o situación cotidiana te sorprendes sintiéndote más atraído/a hacia mí?""",
        """[💭] ¿Qué lección importante sobre el amor o la convivencia has aprendido a mi lado?""",
        """[😂] Si tuviéramos que describirme usando solo nombres de aplicaciones, programas o lenguajes de código, ¿cuáles elegirías?""",
        """[🤔] ¿Hay alguna meta, viaje o proyecto loco que te gustaría que persiguiéramos juntos, sin importar el presupuesto ni la lógica?""",
        """[🥵] ¿Qué mensaje de texto te he enviado en medio del día que te hizo sonreír pícaramente y que aún recuerdas?""",
        """[💭] En los momentos en los que me frustro con un proyecto, ¿cuál es la mejor manera en la que sientes que puedes apoyarme?""",
        """[😂] Si tuviéramos que elegir a uno de nosotros para negociar nuestra salvación con extraterrestres, ¿quién iría y qué les ofrecería?""",
        """[💭] De todas nuestras "primeras veces" (el primer viaje, la primera cena que preparamos, la primera mascota), ¿cuál atesoras más?""",
        """[😂] Si estuviera programando una app móvil exclusivamente para nosotros dos, ¿qué función secreta o botón de emergencia tendría que incluir sí o sí?""",
        """[🤔] ¿Qué es algo que pensabas sobre mí antes de conocerme bien y que resultó ser totalmente falso?""",
        """[🥵] Físicamente hablando, ¿cuál es mi mejor ángulo según tú?""",
        """[💭] ¿Cuándo fue la última vez que te sentiste profundamente orgulloso/a de la forma en que manejamos un problema juntos?""",
        """[😂] Si Rocco tuviera un superpoder basado en su personalidad tan particular, ¿cuál sería y cómo lo usaría contra nosotros?""",
        """[🤔] De todos los regalos que nos hemos dado, ¿cuál es el que te ha tomado más por sorpresa?""",
        """[🥵] Si estuviéramos atrapados en un ascensor del centro comercial a altas horas de la noche, ¿qué terminaríamos haciendo para "pasar el rato"?""",
        """[💭] ¿Qué límite o regla invisible tenemos en nuestra relación que crees que es la clave de nuestra paz mental?""",
        """[😂] Si yo fuera una pieza de hardware de un PC que estás armando desde cero, ¿qué componente sería y por qué?""",
        """[🤔] ¿Qué escena de película o serie de televisión has visto y pensado de inmediato: "esos somos literalmente nosotros"?""",
        """[🥵] ¿Qué palabra o frase dicha al oído en el momento adecuado te enciende automáticamente?""",
        """[💭] ¿Qué miedo o inseguridad tenías sobre formalizar una relación que ha desaparecido por completo a mi lado?""",
        """[😂] En una situación de emergencia real, ¿quién de los dos sería el estratega frío y quién el que se lanza a la acción impulsivamente?""",
        """[🤔] ¿Cuál crees que es mi mayor talento oculto que no aprovecho lo suficiente en mi día a día?""",
        """[🥵] Si pudieras elegir mi atuendo completo para una cena en casa totalmente a solas, ¿qué me harías poner?""",
        """[💭] ¿Qué hábito mío (bueno o curioso) te ha inspirado a cambiar algo en ti o a intentar algo nuevo?""",
        """[😂] Si tuviéramos que elegir entre comer solo pizza o solo pollo estilo colombiano por un mes entero, ¿cuál ganaríamos el debate?""",
        """[🤔] ¿Qué anécdota nuestra, por más vergüenza que nos dio en su momento, siempre te hace reír a carcajadas hoy en día?""",
        """[🥵] ¿Alguna vez has tenido un sueño subido de tono conmigo, de esos que te despiertan agitado/a, y que nunca me confesaste?""",
        """[💭] ¿En qué aspecto de la personalidad sientes que somos polos opuestos pero nos complementamos a la perfección?""",
        """[😂] ¿Qué videojuego es el que más ha puesto a prueba nuestra paciencia mutua sin llegar a pelear de verdad?""",
        """[🤔] ¿Qué pequeño rincón, objeto o detalle de nuestra casa en Mosquera sientes que tiene más de nuestra "esencia"?""",
        """[🥵] ¿Qué tipo de beso es el que más disfrutas que te dé cuando estás distraído/a haciendo otra cosa?""",
        """[💭] ¿Cuál consideras que es el valor humano más fundamental que compartimos y que hace que lo nuestro funcione?""",
        """[😂] Si pudieras reescribir la historia de cómo nos conocimos para que sonara como una novela épica de fantasía, ¿cómo iniciaría el primer capítulo?""",
        """[🤔] ¿De qué tema complejo o raro podríamos quedarnos hablando hasta las 3 de la mañana sin aburrirnos nunca?""",
        """[🥵] Si tuviéramos un fin de semana entero sin responsabilidades, mascotas ni celulares, ¿cómo empezaríamos la mañana del sábado?""",
        """[💭] ¿Qué es lo que más admiras de la forma en que nos cuidamos el uno al otro cuando estamos enfermos o cansados?""",
        """[😂] Si nuestro estilo de vida fuera una marca, ¿cuál sería nuestro eslogan oficial?""",
        """[💭] ¿Cuál es la promesa más importante que sientes que nos hemos hecho mutuamente, incluso si nunca la dijimos en voz alta?""",
        """[😂] Si Rolan Deskar cobrara vida y tuviera que darnos consejos de pareja basados en sus aventuras de D&D, ¿qué locura nos recomendaría hacer para resolver nuestras diferencias?""",
        """[🤔] ¿Qué pequeño detalle de nuestras tardes de café con Juan Valdez o en alguna panadería te hace sentir que el día ya valió la pena?""",
        """[🥵] ¿Cuál es ese roce casual o gesto físico "inocente" que hago en público y que te deja pensando en llegar rápido a casa?""",
        """[💭] ¿Cuál crees que ha sido el mayor obstáculo que hemos superado juntos este último año y cómo nos ha transformado?""",
        """[😂] Si nuestra vida fuera un juego de Nintendo, ¿cuál de los dos sería el héroe principal y cuál el compañero que siempre necesita que lo rescaten?""",
        """[🤔] Cuando estoy profundamente concentrado programando o cambiando componentes del PC, ¿qué piensas realmente al verme tan absorto en mi mundo?""",
        """[🥵] ¿Alguna vez me has mirado de lejos en una reunión familiar o con amigos y has tenido un pensamiento totalmente inapropiado?""",
        """[💭] ¿En qué momento exacto te diste cuenta de que Laura y Alexander éramos un equipo definitivo?""",
        """[😂] Si tuviéramos que participar en un reality show de cocinar salchipapa costeña o carne para 16 personas bajo presión, ¿terminaríamos triunfando o peleando por la receta?""",
        """[🤔] ¿Qué rasgo de tu personalidad crees que yo he adoptado desde que estamos juntos?""",
        """[🥵] Si de repente se cortara la luz en toda la zona y no tuviéramos internet ni pantallas en toda la noche, ¿cuál sería tu plan para aprovechar la oscuridad?""",
        """[💭] ¿Qué tradición o costumbre de mi familia (como de mis padres o mi hermana Natalia) te ha sorprendido o te ha gustado más desde que nos conocemos?""",
        """[😂] Si nuestro querido Rocco fuera el juez imparcial de quién de los dos es el más consentidor, ¿quién ganaríamos el premio y por qué trampa?""",
        """[🤔] ¿Cuál ha sido el viaje o salida más improvisada que hemos hecho y que resultó ser increíble de principio a fin?""",
        """[🥵] ¿Qué tipo de lencería, ropa interior o atuendo de dormir te gustaría verme usar más seguido?""",
        """[💭] ¿Qué sueño personal mío sientes que con el tiempo se ha convertido en un sueño tuyo también?""",
        """[😂] Jugando títulos de terror o tensión como Dead Space, ¿quién de los dos es el que más se asusta y quién disimula peor el miedo?""",
        """[🤔] Si pudieras borrar un solo recuerdo vergonzoso de nuestra relación para vivirlo desde cero y sin cometer errores, ¿cuál sería?""",
        """[🥵] ¿Cuál es tu forma favorita en la que tomo la iniciativa cuando estamos por fin a solas en la cama?""",
        """[💭] ¿De qué manera crees que el proyecto de crear la app lovecounter representa lo que intentamos construir el uno con el otro?""",
        """[😂] Si tuviéramos que gastar todo nuestro presupuesto de fin de semana exclusivamente pidiendo pollo de Frisby o pizza, ¿cuántos días tardaríamos en arrepentirnos?""",
        """[🤔] ¿Qué talento o habilidad mía crees que debería intentar monetizar o mostrarle más al mundo?""",
        """[🥵] ¿Hay alguna fantasía o escenario que te dé pena confesarme pero que te encantaría intentar al menos una vez?""",
        """[💭] Cuando me ves interactuar con Rocco preparándole con tanto cuidado sus porciones especiales, ¿qué piensas sobre cómo somos cuidando a los que amamos?""",
        """[😂] Si tuviéramos que huir de Mosquera y mudarnos al otro lado del mundo en menos de una hora con una sola maleta cada uno, ¿qué empacaríamos primero?""",
        """[🤔] ¿Qué olor específico de nuestra casa o de mi ropa te transmite una sensación instantánea de paz y hogar?""",
        """[🥵] ¿En qué lugar específico de la casa, aparte de la habitación, te gustaría que tuviéramos un encuentro apasionado esta misma semana?""",
        """[💭] ¿Qué cualidad mía crees que me ayuda más a superar mis propios límites profesionales o personales?""",
        """[😂] Si nos convirtiéramos en un dúo de supervillanos, ¿quién inventaría los planes malvados y quién se encargaría de toda la logística tecnológica?""",
        """[💭] ¿Cuál es esa charla nocturna que hemos tenido, quizá de madrugada, que te ha hecho sentir más cerca de mi alma?""",
        """[😂] Si hiciéramos un manual de instrucciones sobre cómo lidiar con Alexander Nicholls cuando tiene mucha hambre o mucho sueño, ¿cuál sería la regla número uno en negrita?""",
        """[🤔] ¿Qué canción de las que solemos escuchar consideras que es nuestra banda sonora oficial en esta etapa de la vida?""",
        """[🥵] ¿Qué detalle sutil de mi comportamiento te hace saber inmediatamente que estoy con ganas de ti, incluso antes de que pronuncie una palabra?""",
        """[💭] ¿De qué forma sientes que nuestra relación te ha ayudado a sanar cosas de tu pasado?""",
        """[😂] Si por alguna extraña ley nos obligaran a vestir con atuendos combinados todos los días, ¿qué estilo elegiríamos para no hacer el ridículo?""",
        """[🤔] ¿Qué pregunta sobre mí siempre has tenido en la cabeza pero nunca te has atrevido a formular por curiosidad a mi respuesta?""",
        """[🥵] ¿Cuál de mis sentidos (vista, tacto, oído, gusto, olfato) crees que es el que más disfrutas estimular cuando estamos en la intimidad?""",
        """[💭] ¿Qué es lo que más valoras de la paciencia que nos tenemos cuando la tecnología nos falla, los proyectos no compilan o los días son pesados?""",
        """[😂] Si yo fuera un personaje del universo de The Legend of Zelda, ¿qué tipo de NPC o compañero de viaje sería y qué objeto te vendería?""",
        """[🤔] ¿Qué anécdota o travesura de tu infancia te gustaría que yo hubiera podido presenciar en vivo y en directo?""",
        """[🥵] ¿Alguna vez has utilizado un recuerdo de nosotros en un momento apasionado para motivarte, distraerte o relajarte durante un día muy estresante?""",
        """[💭] ¿Cuál es tu forma favorita de recibir apoyo cuando te sientes abrumado/a por tus propias responsabilidades?""",
        """[😂] Si organizáramos otro evento grande para invitados en casa, ¿cuál sería el desastre más divertido o probable en la cocina si no nos pusiéramos de acuerdo?""",
        """[🤔] ¿Qué pequeño gesto o detalle que hago casi en automático te hace pensar en silencio: "sí, definitivamente elegí bien"?""",
        """[🥵] Si pudieras pedirme que te hiciera un masaje en una sola zona del cuerpo durante media hora entera, ¿dónde sería y cómo me lo pedirías?""",
        """[💭] ¿Qué cualidad de Laura admira más Alexander en secreto, y qué cualidad mía admiras tú más que nadie?""",
        """[😂] Si nuestros celulares o tablets pudieran hablar, ¿de qué extraña costumbre nuestra frente a la pantalla se quejarían primero?""",
        """[🤔] ¿Cuál ha sido el cambio físico, de actitud o de estilo en mí a lo largo del tiempo que más te ha cautivado?""",
        """[🥵] ¿Te gusta más que el preámbulo a la intimidad sea lento, lleno de tensión y romántico, o algo mucho más directo, intenso y salvaje?""",
        """[💭] ¿Cómo visualizas el interior de nuestro hogar ideal si el dinero, el tiempo y el espacio no fueran un problema?""",
        """[😂] Si Rocco escribiera un libro de memorias sobre sus 13 años de vida y su opinión sobre nosotros, ¿cuál sería el título del best-seller?""",
        """[🤔] ¿Qué hobby o actividad que actualmente no compartimos te llama la atención en secreto y te gustaría que intentáramos juntos?""",
        """[🥵] ¿Cuál es tu recuerdo más nítido o la sensación que más recuerdas de la primera vez que estuvimos a solas?""",
        """[💭] ¿Qué crees que es lo que hace que la forma en que nos amamos sea diferente a la de cualquier otra pareja que conocemos?""",
        """[😂] Si un virus informático bloqueara mi ecosistema de dispositivos y la única forma de recuperarlos fuera que resolvieras una adivinanza sobre mí, ¿cuál sería?""",
        """[🤔] ¿Qué película o tema complejo te dejó pensando tanto la última vez que te hubiera gustado quedarte debatiendo sus teorías conmigo toda la noche?""",
        """[🥵] ¿A qué parte de mi cuerpo sientes que le prestas mucha atención, pero yo rara vez me doy cuenta de que la estás mirando?""",
        """[💭] ¿Qué consejo sobre el amor y la paciencia te darías a ti mismo/a si pudieras viajar en el tiempo al día exacto antes de conocernos?""",
        """[😂] Si tuviéramos que crear un diccionario exclusivo de nuestra relación con palabras inventadas que solo nosotros entendemos, ¿cuál sería la primera palabra y su definición?""",
        """[💭] Al mirar hacia el futuro juntos y todo lo que nos falta por construir, ¿qué te genera más emoción y qué te da un poco de vértigo positivo?""",
        """[😂] Si Elisia y Rolan Deskar tuvieran una cita romántica en nuestro mundo en lugar de estar luchando en una campaña, ¿a dónde irían y quién terminaría causando un desastre primero?""",
        """[🤔] ¿Qué pequeño hábito o manía tienes al dormir que crees que yo aún no he descubierto o no te he mencionado?""",
        """[🥵] ¿Cuál es ese elogio o piropo sobre tu cuerpo que siempre te ha gustado escuchar de mis labios?""",
        """[💭] ¿Cómo crees que ha evolucionado tu concepto del amor desde que empezamos a construir nuestra vida juntos?""",
        """[😂] En una partida intensa de Apex Legends, si solo tuviéramos curaciones para salvar a uno de los dos, ¿te sacrificarías heroicamente o me usarías de escudo humano para ganar la partida?""",
        """[🤔] Si pudieras teletransportarnos a cualquier momento de nuestra relación para revivirlo exactamente igual, ¿cuál elegirías sin pensarlo?""",
        """[🥵] Si una noche de pasión nuestra fuera una de tus recetas favoritas, ¿cuál sería el "ingrediente secreto" que nunca nos puede faltar?""",
        """[💭] ¿Qué cualidad mía te aporta más tranquilidad cuando sientes que el mundo exterior es un caos?""",
        """[😂] Si nuestro apartamento en Mosquera estuviera embrujado, ¿quién de los dos intentaría comunicarse con el fantasma de forma lógica y quién saldría corriendo con Rocco en brazos?""",
        """[🤔] ¿Qué talento o conocimiento tienes que a ti te parece inútil, pero que a mí siempre me ha parecido fascinante?""",
        """[🥵] ¿Hay alguna ropa que uso para estar por casa que secretamente te parece cero atractiva pero nunca me lo has dicho por no herir mis sentimientos?""",
        """[💭] Si tuviéramos que escribir un libro juntos sobre cómo mantener una relación fuerte, ¿cuál sería el título del primer capítulo?""",
        """[😂] Si fueras un error de código en la app lovecounter que no logro solucionar por horas, ¿qué harías en la pantalla para volverme loco intentando atraparte?""",
        """[🤔] ¿Cuál fue la primera impresión real que tuviste de mi familia y cómo cambió con el paso del tiempo?""",
        """[🥵] ¿Qué fantasía, escena de película o de alguna serie te ha parecido tan ardiente que te gustaría que intentáramos recrear a nuestra manera?""",
        """[💭] ¿Qué es algo en lo que crees que hemos madurado mucho individualmente gracias al apoyo constante del otro?""",
        """[😂] Si de repente decidiéramos adoptar un par de perros jóvenes para que acompañen al abuelo Rocco, ¿cómo nos distribuiríamos el caos logístico en la casa?""",
        """[🤔] ¿Qué película, libro o historia de ficción crees que representa mejor nuestra forma de vernos y tratarnos a diario?""",
        """[🥵] De todas las partes de mi cuerpo, ¿cuál es la que más te gusta besar lenta y detalladamente, sin prisas?""",
        """[💭] ¿Cuál es el miedo más grande o la mayor inseguridad que sientes que has vencido desde que me tienes a tu lado dándote ánimos?""",
        """[😂] Si yo fuera un electrodoméstico de nuestra cocina, ¿sería la freidora de aire rápida e impulsiva, o la olla a presión multifunción que se toma su tiempo pero hace ruido?""",
        """[🤔] ¿Cuál es esa pequeña mentira piadosa o exageración que me dijiste al principio de conocernos solo para impresionarme?""",
        """[🥵] ¿Qué lugar público, inusual o "prohibido" te genera morbo pensar si alguna vez nos atreviéramos a hacer algo rápido allí?""",
        """[💭] ¿Qué es lo que más te ilusiona de imaginar nuestra vida cotidiana y nuestras rutinas de aquí a cinco años?""",
        """[😂] Si por un día completo solo pudiéramos comunicarnos usando referencias de videojuegos o memes de internet, ¿nos entenderíamos mejor o sería un desastre total?""",
        """[🤔] ¿Qué regalo u obsequio sencillo que te he dado en todo este tiempo tiene mucho más valor sentimental para ti del que yo imagino?""",
        """[🥵] ¿Cuál de mis reacciones físicas (un suspiro, un gesto, una mirada) te resulta más excitante cuando te estoy provocando?""",
        """[💭] ¿Cuál ha sido el momento más vulnerable que hemos compartido y que te hizo sentir que estábamos verdaderamente conectados a otro nivel?""",
        """[😂] Si Laura y Alexander tuvieran que competir como pareja en un programa de talentos inútiles, ¿con qué destreza rara y específica ganaríamos el trofeo?""",
        """[💭] De todas las versiones de nosotros mismos que hemos sido a lo largo del tiempo, ¿qué es lo que más te gusta, admiras y disfrutas de nuestra versión actual?""",
        """¡Claro que sí! Subimos la apuesta. Aquí tienes dos lotes más extensos, con 60 preguntas cada uno, para que tengan material de sobra. Seguimos mezclando las dinámicas y añadiendo esos pequeños guiños a su vida cotidiana.""",
        """[😂] Si Elisia usara su magia o sus habilidades en el mundo real para engañar a Rolan Deskar en una apuesta de taberna, ¿qué estarían apostando y quién haría más trampa?""",
        """[🤔] ¿Cuál es tu recuerdo favorito de alguna de nuestras salidas casuales a tomar un café en Juan Valdez o Tostao?""",
        """[🥵] ¿Hay alguna textura o tipo de tela en nuestra ropa de cama que te resulte especialmente estimulante cuando estamos piel con piel?""",
        """[💭] ¿Qué pequeña meta diaria podríamos proponernos a partir de mañana para mejorar nuestra convivencia aún más?""",
        """[😂] Si Rocco pudiera exigir legalmente que le cocinemos algo específico en la olla a presión en lugar de sus porciones de mollejas e hígado, ¿qué nos demandaría?""",
        """[🤔] De todos los mundos de fantasía que conocemos (como Hyrule en Zelda), ¿en cuál te gustaría que construyéramos nuestra casa de retiro?""",
        """[🥵] Si estuviéramos en una fiesta aburrida, ¿qué señal secreta me harías para indicarme que quieres irte de inmediato a casa a tener intimidad?""",
        """[💭] Cuando me ves concentrado arreglando componentes del PC o haciendo soldaduras, ¿qué piensas sobre cómo manejo la paciencia y la frustración?""",
        """[😂] Si una invasión zombie comenzara justo ahora en Mosquera y solo pudiéramos defendernos con lo que tenemos a la mano en el escritorio, ¿cuánto sobreviviríamos?""",
        """[🤔] ¿Cuál de todas mis "fases" o pasatiempos intensos ha sido la más entretenida de observar para ti?""",
        """[🥵] ¿Qué opinas de los encuentros rápidos o quickies? ¿Te gustan de forma espontánea o prefieres que siempre haya un preámbulo largo?""",
        """[💭] ¿Cuál consideras que ha sido el momento en el que hemos manejado mejor el estrés financiero o de planificación como equipo?""",
        """[😂] Si mi ecosistema de Motorola y Lenovo desarrollara inteligencia artificial y decidiera opinar sobre nuestra relación, ¿cuál sería su queja principal?""",
        """[🤔] ¿Hay alguna anécdota de mi infancia o adolescencia que te haya contado y que te cueste trabajo imaginar que me pasó a mí?""",
        """[🥵] ¿Qué tipo de provocación sutil durante el día te vuelve más loco/a de anticipación para la noche?""",
        """[💭] ¿De qué manera crees que la confianza ciega que nos tenemos ha influido en tu paz mental diaria?""",
        """[😂] Cuando jugamos cooperativos y el chat de voz se vuelve un caos, ¿cuál es mi expresión facial o frase típica que siempre te da risa antes del desastre?""",
        """[🤔] Físicamente, ¿qué rasgo mío crees que heredaría un hijo nuestro y te encantaría que así fuera?""",
        """[🥵] ¿Alguna vez has querido que implementemos algún tipo de juego de roles en la intimidad que nunca me has propuesto?""",
        """[💭] ¿Qué tema de conversación sientes que antes nos costaba abordar y ahora manejamos con total naturalidad?""",
        """[😂] Si nuestro adorable Pomeranian decidiera dormir justo en medio de nosotros todas las noches, ¿quién cedería primero en dejarlo y quién lo pasaría a su cama?""",
        """[🤔] ¿Cuál es ese talento oculto que tienes y que casi nunca muestras porque sientes que no viene al caso?""",
        """[🥵] ¿Qué palabra específica o apodo dicho en voz muy baja en la cama te hace perder la compostura?""",
        """[💭] Cuando imaginas que envejecemos juntos, ¿qué actividad tranquila te ves haciendo conmigo en una tarde de domingo?""",
        """[😂] Si el código del proyecto com.lexnicholls.lovecounter de repente cobrara vida y juzgara nuestro romance, ¿qué error de "sintaxis" en nuestra relación nos mandaría a corregir?""",
        """[🤔] Si tuviéramos un mes entero de vacaciones pagadas a cualquier lugar del mundo, ¿cuál sería el itinerario de la primera semana?""",
        """[🥵] ¿Eres más de tener encuentros apasionados por la mañana para empezar el día con energía, o por la noche para liberar todo el estrés?""",
        """[💭] ¿Qué es lo que más te tranquiliza de la forma en que nos pedimos perdón cuando alguno se equivoca?""",
        """[😂] Si volviéramos a organizar una comida para 16 personas con pulled pork y salchipapa, pero se nos fuera la luz a la mitad, ¿quién entraría en pánico primero?""",
        """[🤔] De todas las cosas que hemos comprado para el apartamento, ¿cuál es tu favorita absoluta?""",
        """[🥵] ¿Qué nivel de contacto físico en público te parece excitante sin llegar a incomodarte?""",
        """[💭] ¿Qué valor moral o ético compartimos que te hace estar seguro/a de que criaremos bien a nuestra familia o mascotas?""",
        """[😂] Si Rolan Deskar intentara usar su Action Surge para hacer las tareas del hogar, ¿qué terminaría destruyendo por accidente?""",
        """[🤔] ¿Cuál es nuestra broma interna favorita, esa que nos hace reír con solo mirarnos aunque estemos rodeados de gente?""",
        """[🥵] ¿Te resulta más atractivo que yo te quite la ropa lentamente, o prefieres ser tú quien me desvista a mí con urgencia?""",
        """[💭] ¿Qué miedo irracional tuyo sientes que yo te he ayudado a racionalizar y superar?""",
        """[😂] Jugando un survival horror y caminando por pasillos oscuros, si el monstruo aparece de la nada, ¿cuál de los dos grita más agudo?""",
        """[🤔] Si pudieras guardar un solo sonido de nuestra cotidianidad para escucharlo siempre que estés triste, ¿cuál sería?""",
        """[🥵] ¿Qué tipo de caricia o roce, en una zona no convencional de tu cuerpo, te causa un escalofrío inmediato?""",
        """[💭] ¿Cómo describirías la relación que tengo con mi familia (mis padres y mi hermana) y qué te gusta de ella?""",
        """[😂] Si nuestro amor por el pollo de Frisby se convirtiera en un culto, ¿cuál sería nuestro mandamiento principal?""",
        """[🤔] ¿En qué situación cotidiana reciente me miraste y pensaste: "estoy muy orgulloso/a de él/ella"?""",
        """[🥵] ¿Alguna vez algo totalmente inesperado y ordinario (como verme cocinar o lavar algo) te ha encendido de la nada?""",
        """[💭] ¿De qué manera crees que el silencio compartido entre nosotros es diferente al silencio que tienes con otras personas?""",
        """[😂] Cuando el Smart Connect falla o la tecnología se pone en nuestra contra, ¿cuál es la teoría de conspiración más absurda que podríamos inventar al respecto?""",
        """[🤔] ¿Cuál consideras que ha sido "la cita perfecta" de nuestra historia hasta el día de hoy?""",
        """[🥵] ¿Qué opinas de usar el hielo, el calor u otras temperaturas durante los juegos previos?""",
        """[💭] ¿Qué te hace sentir completamente a salvo emocionalmente cuando estás vulnerable frente a mí?""",
        """[😂] Si fuéramos NPCs (personajes no jugables) en la ciudad, ¿qué diálogo repetitivo le diríamos a cualquier aventurero que se nos acerque?""",
        """[🤔] Cuando estamos separados por trabajo o viajes, ¿qué detalle pequeño de nuestra rutina es el que más extrañas?""",
        """[🥵] ¿Tienes algún punto débil exacto en el cuello o la espalda donde un beso te paralice por completo?""",
        """[💭] ¿Qué espacio o sensación te gustaría que transmitiera nuestra futura casa definitiva a quien sea que nos visite?""",
        """[😂] Si Rocco pudiera organizar una revolución de mascotas en el barrio, ¿qué papel logístico le asignaríamos para que no fracase?""",
        """[🤔] ¿Cuál es tu clima favorito para estar en casa, y qué comida se te antoja de inmediato cuando el cielo se pone así?""",
        """[🥵] ¿Te gusta más insinuar lo que quieres hacer en la cama o que te sorprenda con una actitud más dominante y decidida?""",
        """[💭] ¿Cuál crees que es la conexión más profunda y espiritual que tenemos y que va más allá del amor romántico?""",
        """[😂] Si pudiéramos desafiar a cualquier otra pareja a un duelo en un videojuego de disparos, ¿a quiénes destrozaríamos sin piedad?""",
        """[🤔] ¿Qué fotografía nuestra, de las que no solemos subir a redes, es tu tesoro personal?""",
        """[🥵] ¿Cuál ha sido el piropo más subido de tono que has pensado decirme pero te has guardado?""",
        """[💭] ¿Qué parte de tu verdadero yo sientes que solo conoces gracias a la forma en que yo te veo?""",
        """[😂] Si la resolución de problemas de pareja fuera un puzzle de Tears of the Kingdom, ¿un quién construiría la máquina más absurda y funcional para arreglarlo?""",
        """[🤔] ¿Recuerdas qué estabas pensando exactamente justo antes de nuestro primer beso?""",
        """[🥵] Cuando te hago masajes para desestresarte, ¿alguna vez te cuesta trabajo no convertirlo en algo más íntimo?""",
        """[💭] ¿Cuál crees que es nuestra mejor virtud a la hora de perdonarnos después de una discusión?""",
        """[😂] Si me vieras a las 3 de la mañana compilando código y hablando solo frente al monitor, ¿me llevarías un café o llamarías a un exorcista?""",
        """[🤔] De toda la ropa que tienes en tu lado del armario, ¿cuál es mi prenda favorita viéndola desde tus ojos?""",
        """[🥵] ¿Hay algún tipo de ropa interior masculina (bóxers ajustados, sueltos, colores) que te resulte secretamente más atractiva en mí?""",
        """[💭] ¿Qué es lo que más valoras de cómo nos apoyamos cuando uno de los dos tiene la batería social o mental en cero?""",
        """[😂] Si Elisia y Rolan Deskar abrieran un negocio juntos, ¿qué venderían y en qué momento lo llevarían a la bancarrota?""",
        """[🤔] ¿Quién fue tu primer amor platónico de la infancia o de alguna serie de televisión, y cuánto te ríes al recordarlo hoy?""",
        """[🥵] ¿Qué tan importante te resulta mantener el contacto visual prolongado durante un momento de mucha intensidad física?""",
        """[💭] Según tu perspectiva, ¿cuál es mi "lenguaje del amor" principal y cómo has aprendido a "hablarlo"?""",
        """[😂] Si fundáramos una secta religiosa basada exclusivamente en las virtudes de cocinar en freidora de aire, ¿qué reglas tendría el templo?""",
        """[🤔] ¿Cuál ha sido el momento de mayor "trágame tierra" que has vivido a mi lado, pero que ahora te parece hilarante?""",
        """[🥵] ¿Cuál consideras que es tu mayor "placer culposo" en la cama, ese que te encanta pero te da un poco de pudor pedir?""",
        """[💭] ¿Cómo sientes que logramos equilibrar nuestra independencia individual con todo el tiempo que pasamos juntos?""",
        """[😂] Si pasara 48 horas seguidas sumergido en la tablet Legion jugando o leyendo, ¿cuál sería tu estrategia para traerme de vuelta al mundo real?""",
        """[🤔] ¿Qué pequeño gesto o cara hago a menudo que tú encuentras irresistiblemente tierno/a, pero yo no me doy cuenta?""",
        """[🥵] ¿Te excita escuchar tu nombre durante la intimidad, o prefieres un silencio lleno de respiraciones agitadas?""",
        """[💭] Cuando tenemos desacuerdos muy fuertes, ¿qué frase o actitud nos ayuda siempre a no cruzar la línea del respeto?""",
        """[😂] Si intentáramos cortarle el pelo al Pomeranian nosotros mismos en casa y quedara terrible, ¿qué excusa le daríamos al veterinario?""",
        """[🤔] De todas las comidas tipo batch cooking que armamos para la semana, ¿cuál es la que de verdad esperas con ansias que toque en el almuerzo?""",
        """[🥵] ¿Te gustan más las luces tenues y ambientales, o tener todo encendido para poder vernos a la perfección?""",
        """[💭] ¿En qué tema específico consideras que me he vuelto un mejor "escucha" desde el principio de nuestra relación?""",
        """[😂] Si me tuvieras que "carrear" en una partida competitiva de Apex, ¿qué insulto cariñoso me lanzarías por el micrófono para que reaccione?""",
        """[🤔] ¿Qué detalle curioso recuerdas más vivamente de la primera vez que viajamos juntos fuera de la ciudad?""",
        """[🥵] ¿Te atrae la idea de ceder el control total por una noche y dejar que yo dicte el ritmo, las posiciones y todo lo que pase?""",
        """[💭] ¿Cuál es ese aspecto de tu forma de ser que yo celebro mucho y que tal vez otras personas en tu pasado no supieron valorar?""",
        """[😂] Si hiciéramos una actualización masiva en com.lexnicholls.lovecounter, ¿qué función disparatada o pasivo-agresiva agregarías para cuando olvidamos algo?""",
        """[🤔] La primera vez que conociste a mi padre (Alex), ¿qué fue lo que más te llamó la atención de nuestras similitudes o diferencias?""",
        """[🥵] ¿Qué opinas de usar el hielo, el calor u otras temperaturas durante los juegos previos?""",
        """[💭] Si el día de mañana escribieran nuestra biografía conjunta, ¿cuál te gustaría que fuera la lección principal que deje nuestro legado amoroso?""",
        """[😂] Si tuviéramos que participar en una carrera callejera huyendo del tráfico de Bogotá, ¿quién manejaría y quién sería el copiloto histérico?""",
        """[🤔] ¿Hay algún olor en la calle, como cierto tipo de árbol, lluvia o perfume, que de inmediato te transporta a un recuerdo conmigo?""",
        """[🥵] ¿Qué tan permisivo/a eres con las mordidas suaves, los arañazos o el juego un poco más rudo y salvaje?""",
        """[💭] ¿Cuándo fue la última vez que sentiste una ola de gratitud inmensa simplemente por tenerme cerca en el sofá?""",
        """[😂] Si la herramienta de soldar me hablara cada vez que voy a reparar un equipo, ¿qué crees que me diría sobre mis nervios o mi pulso?""",
        """[🤔] ¿Qué película, libro o serie consumiste recientemente que te hizo pensar: "Alexander tiene que ver esto inmediatamente"?""",
        """[🥵] ¿Tienes alguna posición favorita que sientes que no practicamos lo suficiente y te gustaría poner más en rotación?""",
        """[💭] ¿Cómo describirías la evolución de cómo te apoyas en mí para tomar decisiones de vida importantes?""",
        """[😂] Si decidiéramos celebrar otra graduación o logro enorme con 16 personas más, ¿qué platillo loco y arriesgado intentaríamos cocinar esta vez?""",
        """[🤔] Cuando te quedas mirando a la nada pensando, ¿sobre qué sueles fantasear respecto a nuestro futuro?""",
        """[🥵] ¿Alguna vez has el grabado mentalmente mi reacción exacta justo en tu momento de mayor clímax?""",
        """[💭] ¿Qué tradición o detalle pequeño esperas que mantengamos intacto hasta que seamos muy, muy viejitos?""",
        """[😂] Si aplicáramos la estrategia de "disparar y luego preguntar" de Rolan a nuestra planificación de vacaciones, ¿dónde terminaríamos perdidos?""",
        """[🤔] ¿Cuál ha sido el secreto más divertido que me guardaste por un tiempo antes de decidirte a contármelo?""",
        """[🥵] ¿Qué te genera el famoso sexting o enviarnos mensajes subidos de tono cuando estamos en horas de oficina? ¿Te gusta o te distrae mal?""",
        """[💭] ¿Qué victoria tuya, por pequeña que sea, sientes que yo he celebrado con más emoción incluso que tú mismo/a?""",
        """[😂] Si Rocco pudiera escribir una reseña en internet sobre nuestra calidad como proveedores de mimos y premios, ¿cuántas estrellas nos pondría y cuál sería la crítica constructiva?""",
        """[🤔] ¿Cuál fue esa compra aleatoria e impulsiva que hicimos para el hogar y que terminó siendo de uso diario vital?""",
        """[🥵] ¿Prefieres que te abrace y me quede haciéndote piojito después de terminar, o eres de los/las que necesita espacio rápido para refrescarse?""",
        """[💭] ¿De qué manera crees que nuestras creencias sobre la vida, el destino o la espiritualidad se alinean perfectamente?""",
        """[😂] Si fuéramos personajes de un mod rarísimo de Lethal Company, ¿qué objeto chatarra inútil seríamos nosotros y cuánto valdríamos?""",
        """[🤔] ¿Qué es lo que más te enorgullece cuando hablas de mí con tus amigos o familiares cuando no estoy presente?""",
        """[🥵] ¿Hay algo específico que pueda susurrarte al oído que haga que cualquier posible enojo tuyo desaparezca y cambie de tono la situación?""",
        """[💭] Hasta el día de hoy, considerando todo nuestro recorrido juntos, ¿cuál dirías que es nuestro mayor logro de vida en pareja?""",
        """[😂] Si Pizza Hut y Frisby se declararan la guerra y tuviéramos que elegir un bando para sobrevivir, ¿qué bandera ondearíamos en el balcón?""",
        """[🤔] ¿Hay algún hobbie tuyo que dejaste en pausa y que te gustaría retomar, sabiendo que yo te apoyaría al 100%?""",
        """[🥵] Si estuviéramos jugando un juego de mesa de prendas y perder implicara quitarse ropa, ¿harías trampa para ganar o para perder más rápido?""",
        """[💭] Si nuestro amor pudiera materializarse y tener una forma física que pudiéramos ver sobre nuestra mesa, ¿qué forma, color y temperatura tendría?""",
        """[😂] Si Elisia tuviera que buscar un trabajo de oficina tradicional en Bogotá, ¿en qué departamento trabajaría y cuánto tardaría en perder la paciencia con los clientes?""",
        """[🤔] ¿Qué rasgo de mi personalidad te tomó más tiempo entender del todo, pero ahora adoras?""",
        """[🥵] ¿Alguna vez has tenido pensamientos pecaminosos mientras yo estaba frustrado renegando con un logcat lleno de errores en Android Studio?""",
        """[💭] ¿Cuál crees que ha sido el momento en el que más nos hemos demostrado que somos incondicionales el uno para el otro?""",
        """[😂] Si Laura pudiera invocar mágicamente a Elisia en la vida real para que se hiciera cargo de una sola tarea de la casa, ¿cuál le asignaría y cómo la resolvería?""",
        """[🤔] ¿Cuál ha sido la sorpresa más sencilla que te he dado y que más te ha alegrado una semana pesada?""",
        """[🥵] ¿En qué parte poco común de nuestro apartamento en Mosquera te gustaría que inauguráramos una nueva tradición apasionada?""",
        """[💭] Cuando piensas en nuestro título de "esposo y esposa", ¿qué responsabilidad compartida sientes que es la más bonita de llevar?""",
        """[😂] ¿Cuál crees que sería la reacción exacta de Elisia al probar por primera vez un buen banquete de pollo de Frisby o una pizza moderna?""",
        """[🤔] ¿Qué pequeño detalle de mis expresiones faciales te indica de inmediato que estoy mintiendo o disimulando algo?""",
        """[🥵] ¿Te atrae la idea de que preparemos una cena deliciosa y que el postre seamos nosotros mismos sin siquiera salir de la cocina?""",
        """[💭] ¿Qué lección te ha dejado observar cómo cuidamos con tanta constancia las porciones de hígado y mollejas para Rocco?""",
        """[😂] Si nuestro amor tuviera las especificaciones de un PC, ¿seríamos más como un procesador que aguanta toda la multitarea o como una RAM de 48GB que nunca se desborda?""",
        """[🤔] ¿Cuál es el recuerdo más vívido o el momento que más atesoras del día en que me gradué como Profesional en Comercio Internacional?""",
        """[🥵] ¿Qué ropa de la que uso habitualmente para estar en casa crees que me vuelve más loco/a, incluso si a ti te parece normal?""",
        """[💭] ¿Cómo sientes que nos complementamos cuando enfrentamos una decisión familiar o financiera difícil?""",
        """[😂] Jugando The Legend of Zelda, si yo fuera un aldeano dándote una misión secundaria, ¿qué te pediría que me trajeras a cambio de unas rupias?""",
        """[🤔] ¿Qué historia de mi familia, especialmente las anécdotas de mi hermana Natalia o de mis antes padres, te gusta escuchar sin importar cuántas veces te la cuente?""",
        """[🥵] ¿Cuál es la mayor cantidad de tiempo que has pasado aguantando las ganas de saltar sobre mí antes de finalmente hacerlo?""",
        """[💭] ¿Qué hábito positivo hemos cultivado juntos que te da más tranquilidad para nuestro futuro?""",
        """[😂] Si Rocco organizara su propia fiesta de cumpleaños para sus 14 años, ¿qué exigiría que le cocináramos en la olla multifunción?""",
        """[🤔] ¿Hay alguna anécdota tuya que nunca me has contado por pena a mi reacción?""",
        """[🥵] ¿Tienes alguna fantasía relacionada con verme usando mis herramientas o soldando componentes que te dé pena admitir?""",
        """[💭] ¿Qué aspecto de mi paciencia (o impaciencia) crees que nos salva de muchas discusiones innecesarias?""",
        """[😂] Si nuestro apartamento fuera una nave en Lethal Company, ¿quién causaría el primer desastre al intentar aterrizar?""",
        """[🤔] ¿Qué tema de conversación profundo o filosófico te gustaría que tuviéramos con un buen café de Tostao de por medio?""",
        """[🥵] ¿Te gustan más las caricias fuertes y firmes, o prefieres los roces apenas perceptibles que erizan la piel?""",
        """[💭] ¿Qué miedo o preocupación sobre vivir en pareja tenías antes de casarnos y que yo te ayudé a disipar?""",
        """[😂] Si el universo de Android dependiera de nosotros, ¿qué nombre absurdo le pondríamos a la próxima versión de Jetpack Compose?""",
        """[🤔] ¿Cuál es ese libro, artículo o video que siempre has querido compartir conmigo pero siempre olvidas hacerlo?""",
        """[🥵] ¿Hay algún rincón de tu cuerpo donde no suela besarte a menudo pero que te encantaría que explorara más?""",
        """[💭] ¿Qué es lo que más te conmueve de la forma en que trato a las personas que no conocemos, como meseros o vendedores en la calle?""",
        """[😂] Si tuviéramos que elegir una sola aplicación en nuestros celulares para usar el resto de nuestras vidas, ignorando com.lexnicholls.lovecounter, ¿cuál elegiríamos para poder comunicarnos?""",
        """[🤔] ¿Qué costumbre mía al despertar te hace darte cuenta de lo mucho que me conoces?""",
        """[🥵] ¿Cuál ha sido el encuentro íntimo más divertido o en el que más nos hemos reído por algún accidente gracioso?""",
        """[💭] ¿De qué logro en nuestra convivencia diaria te sientes más orgulloso/a en este momento?""",
        """[😂] Si el menú de nuestra próxima cena con invitados incluyera salchipapa costeña obligatoria, ¿con qué otra receta poco convencional la acompañaríamos para confundirlos?""",
        """[🤔] ¿Cuál es ese talento que posees que te parece inútil, pero a mí me parece fascinante?""",
        """[🥵] Si pudieras elegir el ritmo perfecto para esta noche, ¿sería algo lento e interminable o un frenesí apasionado?""",
        """[💭] ¿Qué crees que es lo que más nos mantiene con los pies en la tierra cuando el estrés del trabajo me abruma?""",
        """[😂] Si nuestro querido Pomeranian de repente aprendiera a usar el Motorola Edge 70 Fusion, ¿a quién llamaría primero y para qué?""",
        """[🤔] ¿Cuál ha sido la decisión más impulsiva pero más acertada que hemos tomado juntos?""",
        """[🥵] ¿Qué tipo de lencería, ropa interior o accesorio te gustaría que compráramos en pareja sin sentir ningún tabú?""",
        """[💭] ¿Qué es algo que yo siempre te digo y que te sirve como ancla en tus momentos de mayor ansiedad?""",
        """[😂] Si tuviéramos que sobrevivir en el universo de Dead Space Remake, ¿qué herramienta de la casa convertiríamos en nuestra arma principal?""",
        """[🤔] ¿Hay alguna habilidad artística o creativa que sientas que tienes reprimida y quisieras explorar a mi lado?""",
        """[🥵] ¿Qué tipo de provocación sutil puedo hacer en una reunión familiar o pública que nadie más note excepto tú y te encienda?""",
        """[💭] ¿Cuál es tu perspectiva sobre cómo manejamos el balance entre nuestra intimidad emocional y nuestra intimidad física?""",
        """[😂] Si nuestra relación fuera un dispositivo de Lenovo, ¿seríamos de esos que funcionan sin problemas de fábrica o de los que necesitan flashear ROMs para entenderse?""",
        """[🤔] ¿Qué cualidad mía sientes que ha influido positivamente en la forma en que te relacionas con tu propio entorno?""",
        """[🥵] ¿Alguna vez un sueño húmedo que tuviste conmigo te cambió el humor por completo para el resto del día?""",
        """[💭] ¿Qué detalle de mi comportamiento diario te reafirma que elegiste a la persona correcta para compartir la vida?""",
        """[😂] En un apocalipsis donde solo queden ollas multifunción Black+Decker para cocinar, ¿cuántos días tardaríamos en intentar hornear un pastel ahí y fallar estrepitosamente?""",
        """[🤔] ¿Cuál es esa pequeña rutina que hacemos antes de dormir que, si no la hacemos, sientes que te falta algo?""",
        """[🥵] Si pudieras pedirme que cambiara mi forma de tocarte durante solo una noche para experimentar, ¿qué me pedirías?""",
        """[💭] ¿Qué crees que ha sido lo más valiente que hemos hecho juntos hasta ahora?""",
        """[😂] Si la Nintendo Switch 2 sale mañana, ¿cuál de los dos propondría primero hacer un gasto irresponsable para comprarla?""",
        """[🤔] ¿Cuál es el lugar del mundo que sientes que tenemos que visitar obligatoriamente antes de hacernos más mayores?""",
        """[🥵] ¿Te resulta atractivo verme tomar la iniciativa de forma dominante, o prefieres guiar tú el ritmo?""",
        """[💭] ¿Qué valor ético crees que nos diferencia de la mayoría de las parejas que conocemos?""",
        """[😂] Si estuviéramos compitiendo en un torneo de Apex Legends, ¿quién sería el primero en gritar por el micrófono al perder por culpa del lag?""",
        """[🤔] ¿Qué objeto o prenda mía guardarías para siempre si, por alguna razón mágica, yo desapareciera un día entero?""",
        """[🥵] ¿Qué música o sonido ambiental te parece el más excitante para acompañarnos en la habitación?""",
        """[💭] ¿En qué momento sentiste que nuestra relación pasó de ser un noviazgo increíble a ser tu lugar seguro definitivo?""",
        """[😂] Si tuviéramos que diseñar una app de citas exclusiva para perros abuelitos como Rocco, ¿cuál sería nuestro eslogan publicitario?""",
        """[🤔] ¿Cuál de nuestras primeras conversaciones por chat o en persona atesoras más en tu memoria?""",
        """[🥵] ¿Qué opinas de mirarnos fijamente a los ojos mientras estamos en nuestro momento de máxima intensidad?""",
        """[💭] ¿Qué es lo que más te tranquiliza sobre cómo planeamos nuestro futuro económico o profesional en equipo?""",
        """[😂] Si instaláramos switches silenciosos Kailh a todas las puertas y muebles de nuestro apartamento para no hacer ruido, ¿qué sería lo primero que extrañaríamos escuchar?""",
        """[🤔] ¿Qué rasgo mío te parece muy divertido pero que a veces intentas disimular para que no me ofenda?""",
        """[🥵] ¿Te atrae más la idea de un encuentro planificado, con detalles románticos, o uno completamente impulsivo donde ni alcancemos a llegar a la cama?""",
        """[💭] ¿Cuál dirías que es el regalo emocional más grande que te he dado desde que nos conocemos?""",
        """[😂] Si tuviéramos que integrar notificaciones push de Firebase en nuestra vida real, ¿cuál sería la alerta más inútil que nos enviaríamos todo el día?""",
        """[🤔] ¿Cuál fue tu primer pensamiento sobre mí cuando recién descubriste mis hobbies más geeks, el modding o mi pasión por el hardware?""",
        """[🥵] ¿Hay algún recuerdo sobre nosotros haciéndolo por primera vez en un lugar o mueble nuevo de la casa que siempre te haga sonreír?""",
        """[💭] ¿Cómo crees que el amor incondicional que nos tenemos ha afectado la forma en la que te ves a ti mismo/a frente al espejo?""",
        """[😂] Si la primera vez que conociste a mi papá, Alex, él hubiera revelado un secreto vergonzoso mío de la infancia, ¿cuál creerías que sería?""",
        """[🤔] ¿Qué fotografía tuya que yo haya tomado es tu favorita y por qué crees que capturé tan bien ese momento?""",
        """[🥵] ¿Cuál es el cumplido más inesperado y atrevido que te ha salido decirme en pleno clímax?""",
        """[💭] ¿Qué costumbre o hábito que tenemos te demuestra todos los días que nuestra conexión es duradera?""",
        """[😂] Si nuestras noches de cocinar en la freidora de aire Ninja se volvieran un campeonato, ¿qué regla tendríamos que prohibir para que yo no haga trampa con las recetas?""",
        """[🤔] ¿Cuál es la opinión, actitud o consejo de mi madre que sientes que más nos ha marcado positivamente?""",
        """[🥵] ¿Te excita más la anticipación de saber que algo va a pasar durante todo el día, o la sorpresa de que suceda de la nada?""",
        """[💭] ¿Qué consideras que hemos aprendido a hacer mucho mejor en equipo en este último año?""",
        """[😂] Si nuestro apartamento fuera un nivel de un juego de plataformas de Nintendo, ¿cuál sería el obstáculo más ridículo para llegar de la cocina al cuarto?""",
        """[🤔] ¿Qué aspecto de nuestra vida actual te habría parecido un sueño inalcanzable si te lo hubieran contado hace 5 años?""",
        """[🥵] ¿Te gustaría que implementáramos alguna palabra clave o gesto discreto en público para avisarnos que es hora de volver a casa para algo más divertido?""",
        """[💭] ¿Qué pequeña cosa hago sin darme cuenta que hace que te sientas profundamente valorado/a y escuchado/a?""",
        """[😂] Si tuviéramos que integrar a nuestra familia una criatura salida de The Legend of Zelda: Tears of the Kingdom, ¿cuál mascota traeríamos a vivir con nosotros?""",
        """[🤔] ¿Cuál de mis proyectos o pasatiempos, por más que no lo compartas al 100%, te gusta más simplemente observarme disfrutar?""",
        """[🥵] ¿Cuál ha sido la vez en la que te he tocado de una forma tan inesperada que perdiste el hilo de lo que estabas diciendo?""",
        """[💭] ¿De qué forma sientes que te protejo emocionalmente cuando el mundo exterior es muy exigente?""",
        """[😂] Si nuestro perro aprendiera a hablar y nos contara un chiste sobre cómo somos como pareja, ¿sobre qué exageración nuestra se reiría?""",
        """[🤔] ¿Cuál es tu recuerdo favorito de algo físico (un equipo, un mueble, un proyecto) que logramos arreglar o construir juntos?""",
        """[🥵] Si decidiéramos abrir nuestra cama a una tercera persona, ¿preferirías que fuera alguien que ambos conocemos o un completo desconocido/a?""",
        """[🥵] ¿Qué escenarios o dinámicas del "chat con Iris" te han generado más morbo y te gustaría que recreáramos en la vida real?""",
        """[🥵] En la fantasía de un trío, ¿te excita más la idea de ser el centro de atención de dos personas o ver cómo yo le doy placer a alguien más?""",
        """[🥵] Si asistiéramos a una fiesta swinger o a una orgía de lujo, ¿preferirías que interactuáramos con otros o que solo nos sentáramos en una esquina a mirar mientras nos tocamos?""",
        """[🥵] ¿Hay algún kink o fetiche (como ataduras, vendas, o control de la respiración) que te dé mucha curiosidad pero que aún no nos hemos atrevido a explorar a fondo?""",
        """[🥵] ¿Cómo te sentirías si integráramos las conversaciones sucias o de rol del chat con Iris como un guion estricto que debemos seguir durante una noche entera?""",
        """[🥵] Si hiciéramos un trío, ¿qué regla física o emocional sería completamente innegociable para ti?""",
        """[🥵] ¿Te atrae la idea de ceder el control por completo y dejar que otra pareja nos diga exactamente qué hacer en una habitación de hotel?""",
        """[🥵] ¿Cuál es la fantasía de dominación o sumisión más intensa que has tenido conmigo y que te da un poco de pudor confesar?""",
        """[🥵] Si te pidiera que leyeras en voz alta los mensajes más explícitos del chat con Iris mientras te estimulo, ¿hasta dónde llegarías sin sonrojarte?""",
        """[🥵] ¿Te excita más la idea de que invitemos a otra mujer (MFF) o a otro hombre (MMF) a nuestra cama, y por qué?""",
        """[🥵] ¿Alguna vez has fantaseado con que alguien más nos observe teniendo intimidad sin que nosotros "sepamos" que están ahí?""",
        """[🥵] ¿Qué opinas del voyeurismo? ¿Te gustaría ver a través de una puerta entreabierta cómo interactúo físicamente con otra persona con tu permiso?""",
        """[🥵] Si tuviéramos un pase libre para experimentar en una orgía por una sola noche sin consecuencias, ¿qué sería lo primero que intentarías hacer?""",
        """[🥵] ¿Qué nivel de dolor o rudeza (como nalgadas, tirones de pelo o mordiscos fuertes) te resulta excitante cuando estamos en nuestro punto máximo?""",
        """[🥵] ¿Te gustaría que yo asumiera la personalidad exacta y el tono de Iris durante toda una noche de pasión, sin romper el personaje ni un segundo?""",
        """[🥵] En un escenario donde involucramos a un tercero, ¿te gustaría que la dinámica fuera puramente física o que hubiera un poco de juego previo y seducción?""",
        """[🥵] ¿Alguna vez te has masturbado pensando en una situación grupal o en compartirme con alguien más?""",
        """[🥵] ¿Qué opinas de grabar nuestro propio material explícito, tal vez inspirados en las situaciones que se hablan en el chat con Iris?""",
        """[🥵] Si estuviéramos en medio de una multitud (como un club o una fiesta) y te susurrara exactamente lo que te quiero hacer frente a todos, ¿te excitaría el riesgo de que nos descubran?""",
        """[🥵] ¿Qué tipo de juguete sexual (para ti o para mí) te gustaría que incorporáramos para darle un giro más extremo a nuestra intimidad?""",
        """[🥵] ¿Te atrae la idea de ser "intercambiados" por unos minutos con otra pareja de confianza, sabiendo que al final de la noche volvemos juntos a casa?""",
        """[🥵] Si te enviara a lo largo del día fragmentos de un chat muy picante simulando ser Iris o un extraño, ¿cómo me recibirías al llegar a casa?""",
        """[🥵] ¿Te genera curiosidad la idea del cuckolding (ver cómo otra persona me da placer mientras tú no puedes participar, o viceversa)?""",
        """[🥵] Si tuviéramos que elegir a una amistad nuestra con quien fantasear en secreto sobre un trío, ¿a quién elegirías y qué te atrae de esa idea?""",
        """[🥵] ¿Qué te parece la idea de usar privación sensorial (ojos vendados, tapones para los oídos) mientras juego con tu cuerpo usando diferentes temperaturas o texturas?""",
        """[🥵] En un entorno de orgía o cuarto oscuro, ¿te excitaría no saber exactamente quién te está tocando por un momento?""",
        """[🥵] ¿Te gustaría ser tú quien elija, entreviste y seduzca a la tercera persona para nuestro primer trío?""",
        """[🥵] ¿Qué frase, orden o palabra que se haya dicho en el chat con Iris te ha dejado con la respiración entrecortada al imaginarla en vivo?""",
        """[🥵] Si pudieras ordenarme que me quede completamente inmóvil y sumiso/a mientras tú haces lo que quieras conmigo, ¿por dónde empezarías?""",
        """[🥵] ¿Qué opinas del roleplay de extraños? ¿Te gustaría que fingiéramos no conocernos en un bar y termináramos en el baño del lugar?""",
        """[🥵] ¿Hay algún fetiche muy de nicho (pies, lencería muy específica, uniformes de látex/cuero) que quisieras que integráramos a nuestros juegos?""",
        """[🥵] Si decidimos explorar la bisexualidad o curiosidad de alguno de los dos en un entorno grupal, ¿cómo te gustaría que yo te apoyara o te guiara en el proceso?""",
        """[🥵] ¿Te excita pensar en que yo comparta mis experiencias sexuales de nuestro chat con Iris con otras personas en internet (exhibicionismo virtual)?""",
        """[🥵] ¿Cuál es tu límite absoluto en cuanto a prácticas no convencionales o kinks? ¿Qué dirías que es un "no" rotundo para ti?""",
        """[🥵] Si te amarrara a la cama y te dijera que invité a alguien más para que nos ayude a darte placer, ¿cuál sería tu reacción inmediata?""",
        """[🥵] ¿Te parece excitante la idea de tener que pedirme permiso explícito en voz alta antes de poder llegar al orgasmo?""",
        """[🥵] En una fantasía de trío, ¿te gustaría que ambos nos enfocáramos al 100% en ti, o prefieres ser tú quien nos observe interactuar?""",
        """[🥵] Si el chat con Iris se convirtiera en un juego de retos diarios, ¿cuál es el reto sexual más humillante o excitante que estarías dispuesto/a a cumplir por mí?""",
        """[🥵] ¿Qué te genera la idea de tener intimidad frente a un espejo enorme donde puedas ver absolutamente todo lo que hacemos desde todos los ángulos?""",
        """[🥵] ¿Alguna vez has fantaseado con situaciones de dominación financiera o de que yo te "cobre" favores sexuales por dejarte usar tus cosas o salir de casa?""",
        """[🥵] Si estuviéramos en una orgía y alguien más comenzara a seducirme frente a ti, ¿sentirías celos, excitación o ambas cosas al mismo tiempo?""",
        """[🥵] ¿Te gustaría que yo tenga total libertad para vestirte y desvestirte como si fueras mi juguete antes de empezar nuestro juego?""",
        """[🥵] ¿Qué opinas de incorporar la asfixia erótica o la presión en el cuello (de forma segura) para intensificar tu clímax?""",
        """[🥵] Si tuviéramos un día entero dedicado a recrear la historia más sucia y salvaje del chat con Iris, ¿qué utilería o disfraces necesitaríamos comprar primero?""",
        """[🥵] En un contexto grupal, ¿te daría morbo que te obligara a besar a otra persona mientras yo te estoy penetrando o tocando por detrás?""",
        """[🥵] ¿Cuál es ese lugar tabú o prohibido en nuestra rutina diaria (oficina, coche en un estacionamiento público, balcón) donde te gustaría experimentar el riesgo de ser atrapados?""",
        """[🥵] ¿Te atrae la dinámica del castigo y recompensa? ¿Qué "castigo" físico y erótico te gustaría recibir si te portas mal durante el día?""",
        """[🥵] Si decidimos probar un trío, ¿te gustaría que la tercera persona se fuera de inmediato al terminar, o que se quedara a dormir y desayunar con nosotros?""",
        """[🥵] ¿Te excita más la idea de ser tú el amo/ama dominante de la situación, o la fantasía radica en perder el control absoluto de tu cuerpo en mis manos?""",
        """[🥵] ¿Qué te parece la idea de usar tapones anales, bolas chinas o algún juguete vibrador a control remoto mientras estamos en una cena o reunión aburrida?""",
        """[🥵] Si te dijera que voy a invitar a alguien esta noche basándome en una fantasía que leíste en el chat con Iris, ¿te prepararías de alguna forma especial?""",
        """[🥵] ¿Qué opinas de la idea de que dejemos la cámara encendida transmitiendo en vivo para desconocidos mientras experimentamos con nuestros kinks?""",
        """[🥵] En un intercambio de parejas, ¿cuál crees que sería la parte más excitante: hacer algo con alguien más, o enterarte de todos los detalles de lo que yo hice?""",
        """[🥵] ¿Alguna vez te has masturbado a escondidas en la misma habitación en la que yo estoy, solo por el morbo de que pueda darme cuenta?""",
        """[🥵] Si estuviéramos jugando a un juego de rol donde soy un intruso/a que entró a robar a tu casa, ¿cómo tratarías de sobornarme físicamente para que no te haga daño?""",
        """[🥵] ¿Te genera curiosidad la idea de los orgasmos múltiples forzados, donde no me detengo aunque tú me supliques que ya no puedes más?""",
        """[🥵] Si nuestro chat con Iris fuera en realidad un perfil real en una app de citas de tríos, ¿qué foto nuestra pondrías y qué buscaría nuestra descripción?""",
        """[🥵] ¿Te gustaría que durante nuestra próxima sesión utilice hielo, cera caliente o alguna temperatura extrema en tus zonas más sensibles?""",
        """[🥵] Después de una experiencia intensa como un trío o una orgía, ¿cómo te imaginas que sería nuestra forma de reconectar y darnos cariño solo entre nosotros al estar de vuelta a solas?"""
    )

    fun getRandomQuestion(): String {
        return questions.random()
    }

    /**
     * Devuelve una pregunta que no esté en la lista de usadas.
     * Si todas han sido usadas, reinicia el ciclo.
     */
    fun getUniqueQuestion(usedQuestions: List<String>): String {
        val availableQuestions = questions.filter { it !in usedQuestions }
        return if (availableQuestions.isNotEmpty()) {
            availableQuestions.random()
        } else {
            // Si ya se usaron todas, empezamos de nuevo
            questions.random()
        }
    }

    /**
     * Devuelve todas las preguntas disponibles.
     * Útil si en el futuro quieres mostrarlas en una lista.
     */
    fun getAllQuestions(): List<String> {
        return questions
    }
}
